# Generated by Django 2.2.3 on 2020-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_memory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
